CREATE DATABASE IF NOT EXISTS campus_app
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE campus_app;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(100) NOT NULL UNIQUE,
  nickname VARCHAR(50) DEFAULT NULL,
  avatar_url VARCHAR(255) DEFAULT NULL,
  grade VARCHAR(20) DEFAULT NULL,
  department VARCHAR(100) DEFAULT NULL,
  student_no VARCHAR(50) DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  bio VARCHAR(255) DEFAULT NULL,

  identity_mode ENUM('real', 'anonymous') NOT NULL DEFAULT 'real',
  student_verified TINYINT(1) NOT NULL DEFAULT 0,
  profile_completed TINYINT(1) NOT NULL DEFAULT 0,

  status ENUM('active', 'banned', 'deleted') NOT NULL DEFAULT 'active',
  last_login_at DATETIME DEFAULT NULL,

  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);